### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by fernandocristan** [drewnoakes/vs-side-scroller#13]
Installing in or out of visual studio 2022 the following error occurs

13/09/2022 08:17:26 - Microsoft VSIX Installer
13/09/2022 08:17:26 - -------------------------------------------
13/09/2022 08:17:26 - vsixinstaller.exe version:
13/09/2022 08:17:26 - 17.3.2093
13/09/2022 08:17:26 - -------------------------------------------
13/09/2022 08:17:26 - Command line parameters:
13/09/2022 08:17:26 - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\Fernando\Desktop\SideScroller.Vsix.vsix
13/09/2022 08:17:26 - -------------------------------------------
13/09/2022 08:17:26 - Microsoft VSIX Installer
13/09/2022 08:17:26 - -------------------------------------------
13/09/2022 08:17:27 - System.BadImageFormatException: Foi feita uma tentativa de se carregar um programa com um formato incorreto. (Exceção de HRESULT: 0x8007000B)
   em VSIXInstaller.App.SetGlobalLogger(IInteropLogger logger)
   em VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   em VSIXInstaller.App.Initialize()
   em System.Threading.Tasks.Task`1.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()

**Comment by drewnoakes** [comment]
@fernandocristan apologies for the delay. I suspect the VSIX file was corrupted somehow. Could you (or anyone who else who hits this) please try downloading it again from the marketplace?

I'll close this for now, but can re-open it if it turns out to be an issue related to this repo.

**Comment by fernandocristan** [comment]
hello, it didn't work

instalation log

11/01/2023 08:22:12 - Microsoft VSIX Installer
11/01/2023 08:22:12 - -------------------------------------------
11/01/2023 08:22:12 - vsixinstaller.exe version:
11/01/2023 08:22:12 - 17.3.2093
11/01/2023 08:22:12 - -------------------------------------------
11/01/2023 08:22:12 - Command line parameters:
11/01/2023 08:22:12 - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\Fernando\Desktop\SideScroller.Vsix (1).vsix
11/01/2023 08:22:12 - -------------------------------------------
11/01/2023 08:22:12 - Microsoft VSIX Installer
11/01/2023 08:22:12 - -------------------------------------------
11/01/2023 08:22:12 - System.BadImageFormatException: Foi feita uma tentativa de se carregar um programa com um formato incorreto. (Exceção de HRESULT: 0x8007000B)
   em VSIXInstaller.App.SetGlobalLogger(IInteropLogger logger)
   em VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   em VSIXInstaller.App.Initialize()
   em System.Threading.Tasks.Task`1.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()

**Comment by fernandocristan** [comment]
hello, i downloaded and it didn't work

instalation log

11/01/2023 08:22:12 - Microsoft VSIX Installer
11/01/2023 08:22:12 - -------------------------------------------
11/01/2023 08:22:12 - vsixinstaller.exe version:
11/01/2023 08:22:12 - 17.3.2093
11/01/2023 08:22:12 - -------------------------------------------
11/01/2023 08:22:12 - Command line parameters:
11/01/2023 08:22:12 - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\Fernando\Desktop\SideScroller.Vsix (1).vsix
11/01/2023 08:22:12 - -------------------------------------------
11/01/2023 08:22:12 - Microsoft VSIX Installer
11/01/2023 08:22:12 - -------------------------------------------
11/01/2023 08:22:12 - System.BadImageFormatException: Foi feita uma tentativa de se carregar um programa com um formato incorreto. (Exceção de HRESULT: 0x8007000B)
em VSIXInstaller.App.SetGlobalLogger(IInteropLogger logger)
em VSIXInstaller.App.Initialize(Boolean isRepairSupported)
em VSIXInstaller.App.Initialize()
em System.Threading.Tasks.Task`1.InnerInvoke()
em System.Threading.Tasks.Task.Execute()

**Comment by drewnoakes** [comment]
Could you attach the .vsix come to this issue?

I also suggest running "repair" on your VS installation via the installer.

**Comment by fernandocristan** [comment]
Its not possible attach this file type. 

> I also suggest running "repair" on your VS installation via the installer.
Where i do that?

**Comment by fernandocristan** [comment]
Its working, i believe it was may vs. I reinstalled vs and works

**Comment by drewnoakes** [comment]
Thanks for following up.

**Comment by sdifiore** [comment]
I Have the same problem... I just can't install either in Visual Studio  in both version:
1. ------------------------------------------
Microsoft Visual Studio Enterprise 2022 Version 17.6.0
VisualStudio.17.Release/17.6.0+33712.159
Microsoft .NET Framework
Version 4.8.09032 Enterprise
Visual C++ 2022   00482-20500-00051-AA242
Microsoft Visual C++ 2022
ASP.NET and Web Tools   17.6.326.62524
ASP.NET and Web Tools
Azure App Service Tools v3.0.0   17.6.326.62524
Azure App Service Tools v3.0.0
Azure Functions and Web Jobs Tools   17.6.326.62524
Azure Functions and Web Jobs Tools
C# Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Common Azure Tools   1.10
IncrediBuild Build Acceleration   1.6.0.2
Microsoft JVM Debugger   1.0
Node.js Tools   1.5.50201.1 Commit Hash:0a76e2b03608f2fdee0e7d2e38e83d7721149b5f
NuGet Package Manager   6.6.0
Razor (ASP.NET Core)   17.6.0.2326105+37f2727000f6a964584cafb86e69cf0b39baecb7
SQL Server Data Tools   17.6.13.0
Microsoft SQL Server Data Tools
TypeScript Tools   17.0.20329.2001
TypeScript Tools for Microsoft Visual Studio
Visual Basic Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
Visual C++ for Cross Platform Mobile Development (Android)   17.0.33606.364
Visual C++ for Cross Platform Mobile Development (Android)
Visual F# Tools   17.6.0-beta.23174.5+0207bea1afae48d9351ac26fb51afc8260de0a97
Microsoft Visual F# Tools
Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.
2. ------------------------------------------
Microsoft Visual Studio Enterprise 2022 Version 17.5.3
VisualStudio.17.Release/17.5.3+33516.290
Microsoft .NET Framework Version 4.8.09032
ASP.NET and Web Tools   17.5.318.41597
Azure App Service Tools v3.0.0   17.5.318.41597
Azure Functions and Web Jobs Tools   17.5.318.41597
C# Tools   4.5.0-6.23128.14+651d32d8017cfcc60fcbd67383601fa9a3deb145
Common Azure Tools   1.10
IndentRainbowPackage Extension   1.0
Microsoft Azure Tools for Visual Studio   2.9
Microsoft JVM Debugger   1.0
NuGet Package Manager   6.5.0
Rainbow Braces   1.0.88
Colorizes matching brace pairs to make it easy to identify them and their scope. Works for curly brackets, parentheses, and Razor (ASP.NET Core)   17.5.2.2316603+9f1b6856460af1e592d387ebef416eadddac453f
SQL Server Data Tools   17.2.40119.0
TypeScript Tools   17.0.20105.2003
Using Directive Formatter VS2022   2.0
Visual Basic Tools   4.5.0-6.23128.14+651d32d8017cfcc60fcbd67383601fa9a3deb145
Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools
Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.
ZenCoding   1.2.20

The log given is:

18/05/2023 11:00:25 - Microsoft VSIX Installer
18/05/2023 11:00:25 - -------------------------------------------
18/05/2023 11:00:25 - vsixinstaller.exe version:
18/05/2023 11:00:25 - 17.5.4072+gf05bffad0c
18/05/2023 11:00:25 - -------------------------------------------
18/05/2023 11:00:25 - Command line parameters:
18/05/2023 11:00:25 - C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:17.5.33516.290,/appidname:Microsoft Visual Studio Enterprise 2022,/culture:en-US,/noep,C:\Users\difiore\AppData\Local\Temp\VSIXlxvi1orz.vsix
18/05/2023 11:00:25 - -------------------------------------------
18/05/2023 11:00:25 - Microsoft VSIX Installer
18/05/2023 11:00:25 - -------------------------------------------
18/05/2023 11:00:26 - System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at VSIXInstaller.App.SetGlobalLogger(IInteropLogger logger)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   
   VSIXInstaller.App. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
 And the file I'm trying to install is anexed
